app:
  name: "Go Admin"
  env: "development"  # development, production, test
  mode: "development"
  debug: true
  baseUrl: "http://localhost:8080"
  api_prefix: "/api/v1"
  port: 8080

server:
  address: "0.0.0.0:8080"
  mode: "debug"  # debug, release, test

mysql:
  host: "localhost"
  port: 3306
  username: "root"
  password: ""
  database: "go_admin"
  max_idle_conns: 10
  max_open_conns: 100
  conn_max_lifetime: 3600  # seconds

redis:
  host: "localhost"
  port: 6379
  password: ""
  db: 0

jwt:
  secret: "your-secret-key-here"  # Change this in production
  expire_time: 86400  # 24 hours
  issuer: "go-admin"

cache:
  driver: "redis"  # file, redis
  prefix: "goadmin:"
  options:
    ttl: 3600  # seconds
    # File cache options (when driver is "file")
    file_path: "storage/cache"  # Cache file directory
    # Redis cache options (when driver is "redis")
    host: "localhost"
    port: 6379
    password: ""
    db: 0

queue:
  # 默认驱动: redis, database
  driver: "redis"
  # 默认队列名称
  queue: "default"
  # 连接配置 (使用已配置的redis和mysql连接)
  connection:
    redis: "redis://{{.redis.host}}:{{.redis.port}}/{{.redis.db}}"
    database: "mysql://{{.mysql.username}}:{{.mysql.password}}@{{.mysql.host}}:{{.mysql.port}}/{{.mysql.database}}?charset=utf8mb4&parseTime=True&loc=Local"
  # 工作进程配置
  worker:
    # 无任务时休眠时间(秒)
    sleep: 3
    # 最大处理任务数(0表示无限制)
    max_jobs: 0
    # 最大运行时间(0表示无限制)
    max_time: 0
    # 处理完一个任务后休息时间(秒)
    rest: 0
    # 内存限制(MB)
    memory: 128
    # 任务最大重试次数
    tries: 3
    # 任务超时时间(秒)
    timeout: 60
  # 队列配置
  queues:
    # 默认队列
    default:
      # 队列优先级(数字越大优先级越高)
      priority: 1
      # 队列处理进程数
      processes: 1
      # 队列超时时间(秒)
      timeout: 60
      # 队列重试次数
      tries: 3
      # 队列重试等待时间(秒)
      retry_after: 60
      # 队列退避策略(秒)
      backoff: [60, 300, 900]
    # 高优先级队列
    high:
      priority: 2
      processes: 2
      timeout: 30
      tries: 5
      retry_after: 30
      backoff: [30, 60, 180]
    # 低优先级队列
    low:
      priority: 0
      processes: 1
      timeout: 120
      tries: 2
      retry_after: 120
      backoff: [120, 300, 600]

log:
  level: "debug"  # debug, info, warn, error
  filename: "storage/logs/app.log"
  max_size: 100    # megabytes
  max_backups: 3
  max_age: 28      # days
  compress: true

cors:
  allow_origins: ["*"]  # Use specific domains in production
  allow_methods: ["GET", "POST", "PUT", "DELETE", "PATCH", "HEAD", "OPTIONS"]
  allow_headers: ["Origin", "Content-Type", "Accept", "Authorization"]
  expose_headers: ["Content-Length"]
  allow_credentials: true
  max_age: 86400  # seconds

i18n:
  default_locale: "en"
  load_path: "./locales"
  available_locales: ["en", "zh"]

storage:
  driver: "local"  # local, s3
  local:
    path: "storage/uploads"  # 本地存储路径
  s3:
    endpoint: "https://s3.amazonaws.com"  # S3 端点
    access_key_id: ""  # S3 访问密钥 ID
    secret_access_key: ""  # S3 访问密钥
    bucket: "your-bucket"  # S3 存储桶
    region: "us-west-2"  # S3 区域
    use_ssl: true  # 是否使用 SSL 