app:
  name: "go-admin"
  mode: "development"
  port: 8080

database:
  driver: "mysql"
  host: "localhost"
  port: 3306
  username: "root"
  password: "password"
  database: "go_admin"
  max_idle_conns: 10
  max_open_conns: 100
  conn_max_lifetime: 3600

redis:
  host: "localhost"
  port: 6379
  password: ""
  db: 0

jwt:
  secret: "your-secret-key"
  expire: 86400  # 24 hours
  issuer: "go-admin"

cors:
  allow_origins: ["*"]
  allow_methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
  allow_headers: ["Origin", "Content-Type", "Accept", "Authorization"]
  allow_credentials: true
  max_age: 86400

log:
  level: "debug"
  filename: "logs/app.log"
  max_size: 100    # megabytes
  max_backups: 3
  max_age: 28      # days
  compress: true

s3:
  region: "us-west-2"
  bucket: "your-bucket"
  access_key: ""
  secret_key: "" 